-- MySQL Script generated by MySQL Workbench
-- 03/27/17 19:38:47
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `locationvoiturewebdb` DEFAULT CHARACTER SET utf8 ;
USE `locationvoitureWebdb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Voiture`
-- -----------------------------------------------------
CREATE TABLE `Voiture` (
  `idVoiture` INT NOT NULL AUTO_INCREMENT,
  `marque` VARCHAR(45) NULL,
  `model` VARCHAR(45) NULL,
  `matricul` VARCHAR(45) NULL,
  `color` VARCHAR(45) NULL,
  `kilometrage` INT NULL,
  `carburant` VARCHAR(45) NULL,
  `prix` INT NULL,
  `image` VARCHAR(45) NULL,
  `etat` VARCHAR(45) NULL,
  `assurence` VARCHAR(45) NULL,
  PRIMARY KEY (`idVoiture`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = eucjpms;


-- -----------------------------------------------------
-- Table `mydb`.`Utisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Utisateur` (
  `idUtisateur` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `isAdmin` INT NULL,
  PRIMARY KEY (`idUtisateur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Client` (
  `idClient` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  `age` INT NULL,
  `image` VARCHAR(45) NULL,
  `prmis` VARCHAR(45) NULL,
  `fidel` TINYINT(1) NULL,
  PRIMARY KEY (`idClient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Location`
-- -----------------------------------------------------
CREATE TABLE `Location` (
  `idLocation` INT NOT NULL AUTO_INCREMENT,
  `dateDebut` DATETIME NULL,
  `dateFin` DATETIME NULL,
  `idVoiture` INT NULL,
  `idC` INT NULL,
  `prix` INT NULL,
  PRIMARY KEY (`idLocation`),
  INDEX `idVoiture_idx` (`idVoiture` ASC),
  INDEX `idClient_idx` (`idClient` ASC),
  CONSTRAINT `idVoiture`
    FOREIGN KEY (`idVoiture`)
    REFERENCES `Voiture` (`idVoiture`)
 
  CONSTRAINT `idClient`
    FOREIGN KEY (`idC`)
    REFERENCES `Client` (`idClient`)
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Facture`
-- -----------------------------------------------------
CREATE TABLE  `Facture` (
  `idFacture` INT NOT NULL AUTO_INCREMENT,
  `clientName` VARCHAR(45) NULL,
  `clientNNI` VARCHAR(45) NULL,
  `marqueVoiture` VARCHAR(45) NULL,
  `matricul` VARCHAR(45) NULL,
  `asserance` VARCHAR(45) NULL,
  `prixLocation` INT NULL,
  `dateDebut` DATETIME NULL,
  `dateFin` DATETIME NULL,
  PRIMARY KEY (`idFacture`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
